version: '3.6'
services:
  nginx:
    image: nginx:1.14
    # image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./logs/nginx-error.log:/var/log/nginx/error.log
      - ./logs/nginx-access.log:/var/log/nginx/access.log
      # - ./www:/usr/share/nginx/html
      - ./www:/var/www
    ports:
      - 80:80
      # - 443:443
    depends_on:
      - php
      - db
      
  php:
    build: php
    container_name: php
    # environment: 
    #   COMPOSER_AUTH: ${COMPOSER_AUTH}
    volumes:
      # - ./www:/usr/share/nginx/html
      - ./www:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 9000:9000

  composer:
    image: composer:1.9
    command: ["composer", "install"]
    volumes:
      - ./www/laravel:/app

  db:
    image: mysql:8
    container_name: db
    # volumes:
    #   - dbdata:/var/lib/mysql
    #   - ./mysql/my.cnf:/etc/mysql/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306

# Volumes
# volumes:
#   dbdata: